apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  type: LoadBalancer
  selector:
    app: bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
  labels:
    app: bff
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: drugpugacrdev.azurecr.io/bff:2.0
        ports:
        - containerPort: 3000
