apiVersion: v1
kind: Service
metadata:
  name: qr-service
spec:
  type: LoadBalancer
  selector:
    app: qr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-deployment
  labels:
    app: qr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr
  template:
    metadata:
      labels:
        app: qr
    spec:
      containers:
      - name: qr
        image: drugpugacrdev.azurecr.io/qr:1.0
        ports:
        - containerPort: 80
